# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import chat_session_pb2 as chat__session__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat_session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatSessionServiceStub:
    """Service สำหรับจัดการ Chat Session และ Chat Message
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChatSession = channel.unary_unary(
                '/chat_session.v1.ChatSessionService/CreateChatSession',
                request_serializer=chat__session__pb2.CreateChatSessionRequest.SerializeToString,
                response_deserializer=chat__session__pb2.CreateChatSessionResponse.FromString,
                _registered_method=True)
        self.GetChatSession = channel.unary_unary(
                '/chat_session.v1.ChatSessionService/GetChatSession',
                request_serializer=chat__session__pb2.GetChatSessionRequest.SerializeToString,
                response_deserializer=chat__session__pb2.GetChatSessionResponse.FromString,
                _registered_method=True)
        self.ListChatSessions = channel.unary_unary(
                '/chat_session.v1.ChatSessionService/ListChatSessions',
                request_serializer=chat__session__pb2.ListChatSessionsRequest.SerializeToString,
                response_deserializer=chat__session__pb2.ListChatSessionsResponse.FromString,
                _registered_method=True)
        self.AddChatMessage = channel.unary_unary(
                '/chat_session.v1.ChatSessionService/AddChatMessage',
                request_serializer=chat__session__pb2.AddChatMessageRequest.SerializeToString,
                response_deserializer=chat__session__pb2.AddChatMessageResponse.FromString,
                _registered_method=True)
        self.DeleteChatSession = channel.unary_unary(
                '/chat_session.v1.ChatSessionService/DeleteChatSession',
                request_serializer=chat__session__pb2.DeleteChatSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ChatSessionServiceServicer:
    """Service สำหรับจัดการ Chat Session และ Chat Message
    """

    def CreateChatSession(self, request, context):
        """สร้าง Session การสนทนาใหม่
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatSession(self, request, context):
        """ดึงข้อมูล Session พร้อมประวัติการคุยตาม ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatSessions(self, request, context):
        """ดึงรายการ Chat Sessions ของผู้ใช้ (รองรับ Filter ตาม chatbot_id และ Pagination)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddChatMessage(self, request, context):
        """บันทึกข้อความใหม่ลงใน Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChatSession(self, request, context):
        """ลบ Chat Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChatSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChatSession,
                    request_deserializer=chat__session__pb2.CreateChatSessionRequest.FromString,
                    response_serializer=chat__session__pb2.CreateChatSessionResponse.SerializeToString,
            ),
            'GetChatSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatSession,
                    request_deserializer=chat__session__pb2.GetChatSessionRequest.FromString,
                    response_serializer=chat__session__pb2.GetChatSessionResponse.SerializeToString,
            ),
            'ListChatSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatSessions,
                    request_deserializer=chat__session__pb2.ListChatSessionsRequest.FromString,
                    response_serializer=chat__session__pb2.ListChatSessionsResponse.SerializeToString,
            ),
            'AddChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChatMessage,
                    request_deserializer=chat__session__pb2.AddChatMessageRequest.FromString,
                    response_serializer=chat__session__pb2.AddChatMessageResponse.SerializeToString,
            ),
            'DeleteChatSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChatSession,
                    request_deserializer=chat__session__pb2.DeleteChatSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_session.v1.ChatSessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_session.v1.ChatSessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatSessionService:
    """Service สำหรับจัดการ Chat Session และ Chat Message
    """

    @staticmethod
    def CreateChatSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chat_session.v1.ChatSessionService/CreateChatSession',
            chat__session__pb2.CreateChatSessionRequest.SerializeToString,
            chat__session__pb2.CreateChatSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chat_session.v1.ChatSessionService/GetChatSession',
            chat__session__pb2.GetChatSessionRequest.SerializeToString,
            chat__session__pb2.GetChatSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chat_session.v1.ChatSessionService/ListChatSessions',
            chat__session__pb2.ListChatSessionsRequest.SerializeToString,
            chat__session__pb2.ListChatSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chat_session.v1.ChatSessionService/AddChatMessage',
            chat__session__pb2.AddChatMessageRequest.SerializeToString,
            chat__session__pb2.AddChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChatSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chat_session.v1.ChatSessionService/DeleteChatSession',
            chat__session__pb2.DeleteChatSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
