# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import knowledge_file_pb2 as knowledge__file__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_file_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeFileServiceStub:
    """--- gRPC Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateKnowledgeFile = channel.stream_unary(
                '/knowledge_file.v1.KnowledgeFileService/CreateKnowledgeFile',
                request_serializer=knowledge__file__pb2.UploadFileStreamRequest.SerializeToString,
                response_deserializer=knowledge__file__pb2.UploadFileStreamResponse.FromString,
                _registered_method=True)
        self.GetKnowledgeFile = channel.unary_unary(
                '/knowledge_file.v1.KnowledgeFileService/GetKnowledgeFile',
                request_serializer=knowledge__file__pb2.GetKnowledgeFileRequest.SerializeToString,
                response_deserializer=knowledge__file__pb2.GetKnowledgeFileResponse.FromString,
                _registered_method=True)
        self.ListKnowledgeFiles = channel.unary_unary(
                '/knowledge_file.v1.KnowledgeFileService/ListKnowledgeFiles',
                request_serializer=knowledge__file__pb2.ListKnowledgeFilesRequest.SerializeToString,
                response_deserializer=knowledge__file__pb2.ListKnowledgeFilesResponse.FromString,
                _registered_method=True)
        self.DeleteKnowledgeFile = channel.unary_unary(
                '/knowledge_file.v1.KnowledgeFileService/DeleteKnowledgeFile',
                request_serializer=knowledge__file__pb2.DeleteKnowledgeFileRequest.SerializeToString,
                response_deserializer=knowledge__file__pb2.DeleteKnowledgeFileResponse.FromString,
                _registered_method=True)


class KnowledgeFileServiceServicer:
    """--- gRPC Service Definition ---

    """

    def CreateKnowledgeFile(self, request_iterator, context):
        """ประมวลผลและสร้าง Ingestion เอกสารเข้า Vector DB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKnowledgeFile(self, request, context):
        """ดึงข้อมูลเอกสารตาม file_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKnowledgeFiles(self, request, context):
        """ดึงรายการเอกสารทั้งหมดของ Chatbot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKnowledgeFile(self, request, context):
        """ลบเอกสารออกจาก MongoDB และ Vector DB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateKnowledgeFile': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateKnowledgeFile,
                    request_deserializer=knowledge__file__pb2.UploadFileStreamRequest.FromString,
                    response_serializer=knowledge__file__pb2.UploadFileStreamResponse.SerializeToString,
            ),
            'GetKnowledgeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKnowledgeFile,
                    request_deserializer=knowledge__file__pb2.GetKnowledgeFileRequest.FromString,
                    response_serializer=knowledge__file__pb2.GetKnowledgeFileResponse.SerializeToString,
            ),
            'ListKnowledgeFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKnowledgeFiles,
                    request_deserializer=knowledge__file__pb2.ListKnowledgeFilesRequest.FromString,
                    response_serializer=knowledge__file__pb2.ListKnowledgeFilesResponse.SerializeToString,
            ),
            'DeleteKnowledgeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKnowledgeFile,
                    request_deserializer=knowledge__file__pb2.DeleteKnowledgeFileRequest.FromString,
                    response_serializer=knowledge__file__pb2.DeleteKnowledgeFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'knowledge_file.v1.KnowledgeFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('knowledge_file.v1.KnowledgeFileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeFileService:
    """--- gRPC Service Definition ---

    """

    @staticmethod
    def CreateKnowledgeFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(  # type: ignore
            request_iterator,
            target,
            '/knowledge_file.v1.KnowledgeFileService/CreateKnowledgeFile',
            knowledge__file__pb2.UploadFileStreamRequest.SerializeToString,
            knowledge__file__pb2.UploadFileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKnowledgeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/knowledge_file.v1.KnowledgeFileService/GetKnowledgeFile',
            knowledge__file__pb2.GetKnowledgeFileRequest.SerializeToString,
            knowledge__file__pb2.GetKnowledgeFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKnowledgeFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/knowledge_file.v1.KnowledgeFileService/ListKnowledgeFiles',
            knowledge__file__pb2.ListKnowledgeFilesRequest.SerializeToString,
            knowledge__file__pb2.ListKnowledgeFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKnowledgeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/knowledge_file.v1.KnowledgeFileService/DeleteKnowledgeFile',
            knowledge__file__pb2.DeleteKnowledgeFileRequest.SerializeToString,
            knowledge__file__pb2.DeleteKnowledgeFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
