# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import multi_tenant_chatbot_pb2 as multi__tenant__chatbot__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in multi_tenant_chatbot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatbotServiceStub:
    """Service สำหรับจัดการ Chatbot Blueprint / Profile Operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMultiTenantChatbot = channel.unary_unary(
                '/chatbot.v1.ChatbotService/CreateMultiTenantChatbot',
                request_serializer=multi__tenant__chatbot__pb2.CreateMultiTenantChatbotRequest.SerializeToString,
                response_deserializer=multi__tenant__chatbot__pb2.CreateMultiTenantChatbotResponse.FromString,
                _registered_method=True)
        self.GetMultiTenantChatbot = channel.unary_unary(
                '/chatbot.v1.ChatbotService/GetMultiTenantChatbot',
                request_serializer=multi__tenant__chatbot__pb2.GetMultiTenantChatbotRequest.SerializeToString,
                response_deserializer=multi__tenant__chatbot__pb2.GetMultiTenantChatbotResponse.FromString,
                _registered_method=True)
        self.ListMultiTenantChatbots = channel.unary_unary(
                '/chatbot.v1.ChatbotService/ListMultiTenantChatbots',
                request_serializer=multi__tenant__chatbot__pb2.ListMultiTenantChatbotsRequest.SerializeToString,
                response_deserializer=multi__tenant__chatbot__pb2.ListMultiTenantChatbotsResponse.FromString,
                _registered_method=True)
        self.UpdateMultiTenantChatbot = channel.unary_unary(
                '/chatbot.v1.ChatbotService/UpdateMultiTenantChatbot',
                request_serializer=multi__tenant__chatbot__pb2.UpdateMultiTenantChatbotRequest.SerializeToString,
                response_deserializer=multi__tenant__chatbot__pb2.UpdateMultiTenantChatbotResponse.FromString,
                _registered_method=True)
        self.DeleteMultiTenantChatbot = channel.unary_unary(
                '/chatbot.v1.ChatbotService/DeleteMultiTenantChatbot',
                request_serializer=multi__tenant__chatbot__pb2.DeleteMultiTenantChatbotRequest.SerializeToString,
                response_deserializer=multi__tenant__chatbot__pb2.DeleteMultiTenantChatbotResponse.FromString,
                _registered_method=True)


class ChatbotServiceServicer:
    """Service สำหรับจัดการ Chatbot Blueprint / Profile Operations
    """

    def CreateMultiTenantChatbot(self, request, context):
        """สร้าง Chatbot Blueprint ใหม่
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMultiTenantChatbot(self, request, context):
        """ดึงข้อมูล Chatbot Blueprint ตาม ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMultiTenantChatbots(self, request, context):
        """ดึงรายการ Chatbot Blueprint ทั้งหมดของผู้ใช้ (รองรับ Pagination)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMultiTenantChatbot(self, request, context):
        """แก้ไขข้อมูล Chatbot Blueprint (ใช้ FieldMask สำหรับ Partial Update)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMultiTenantChatbot(self, request, context):
        """ลบ Chatbot Blueprint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMultiTenantChatbot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMultiTenantChatbot,
                    request_deserializer=multi__tenant__chatbot__pb2.CreateMultiTenantChatbotRequest.FromString,
                    response_serializer=multi__tenant__chatbot__pb2.CreateMultiTenantChatbotResponse.SerializeToString,
            ),
            'GetMultiTenantChatbot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultiTenantChatbot,
                    request_deserializer=multi__tenant__chatbot__pb2.GetMultiTenantChatbotRequest.FromString,
                    response_serializer=multi__tenant__chatbot__pb2.GetMultiTenantChatbotResponse.SerializeToString,
            ),
            'ListMultiTenantChatbots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMultiTenantChatbots,
                    request_deserializer=multi__tenant__chatbot__pb2.ListMultiTenantChatbotsRequest.FromString,
                    response_serializer=multi__tenant__chatbot__pb2.ListMultiTenantChatbotsResponse.SerializeToString,
            ),
            'UpdateMultiTenantChatbot': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMultiTenantChatbot,
                    request_deserializer=multi__tenant__chatbot__pb2.UpdateMultiTenantChatbotRequest.FromString,
                    response_serializer=multi__tenant__chatbot__pb2.UpdateMultiTenantChatbotResponse.SerializeToString,
            ),
            'DeleteMultiTenantChatbot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMultiTenantChatbot,
                    request_deserializer=multi__tenant__chatbot__pb2.DeleteMultiTenantChatbotRequest.FromString,
                    response_serializer=multi__tenant__chatbot__pb2.DeleteMultiTenantChatbotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.v1.ChatbotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatbot.v1.ChatbotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatbotService:
    """Service สำหรับจัดการ Chatbot Blueprint / Profile Operations
    """

    @staticmethod
    def CreateMultiTenantChatbot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chatbot.v1.ChatbotService/CreateMultiTenantChatbot',
            multi__tenant__chatbot__pb2.CreateMultiTenantChatbotRequest.SerializeToString,
            multi__tenant__chatbot__pb2.CreateMultiTenantChatbotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMultiTenantChatbot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chatbot.v1.ChatbotService/GetMultiTenantChatbot',
            multi__tenant__chatbot__pb2.GetMultiTenantChatbotRequest.SerializeToString,
            multi__tenant__chatbot__pb2.GetMultiTenantChatbotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMultiTenantChatbots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chatbot.v1.ChatbotService/ListMultiTenantChatbots',
            multi__tenant__chatbot__pb2.ListMultiTenantChatbotsRequest.SerializeToString,
            multi__tenant__chatbot__pb2.ListMultiTenantChatbotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMultiTenantChatbot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chatbot.v1.ChatbotService/UpdateMultiTenantChatbot',
            multi__tenant__chatbot__pb2.UpdateMultiTenantChatbotRequest.SerializeToString,
            multi__tenant__chatbot__pb2.UpdateMultiTenantChatbotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMultiTenantChatbot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/chatbot.v1.ChatbotService/DeleteMultiTenantChatbot',
            multi__tenant__chatbot__pb2.DeleteMultiTenantChatbotRequest.SerializeToString,
            multi__tenant__chatbot__pb2.DeleteMultiTenantChatbotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
