# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x06rag.v1\"\xa9\x01\n\x1aRagSearchSimilarRequestDTO\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nchatbot_id\x18\x02 \x01(\t\x12\x12\n\nquery_text\x18\x03 \x01(\t\x12\x12\n\x05top_k\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12\x1e\n\x11knowledge_file_id\x18\x05 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_top_kB\x14\n\x12_knowledge_file_id\"\\\n\x0eRagResponseDTO\x12\x16\n\x0e\x61nswer_message\x18\x01 \x01(\t\x12\x32\n\x07sources\x18\x02 \x03(\x0b\x32!.rag.v1.SearchVectorRecordItemDTO\"S\n\x19SearchVectorRecordItemDTO\x12\r\n\x05score\x18\x01 \x01(\x02\x12\'\n\x06record\x18\x02 \x01(\x0b\x32\x17.rag.v1.VectorRecordDTO\"`\n\x0fVectorRecordDTO\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\x12\x31\n\x08metadata\x18\x03 \x01(\x0b\x32\x1f.rag.v1.MetadataVectorRecordDTO\"\xa1\x01\n\x17MetadataVectorRecordDTO\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nchatbot_id\x18\x02 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x03 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x04 \x01(\x05\x12\x14\n\x0ctext_content\x18\x05 \x01(\t\x12\x13\n\x0bpage_number\x18\x06 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x07 \x01(\t2Y\n\nRagService\x12K\n\rSearchSimilar\x12\".rag.v1.RagSearchSimilarRequestDTO\x1a\x16.rag.v1.RagResponseDTOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAGSEARCHSIMILARREQUESTDTO']._serialized_start=22
  _globals['_RAGSEARCHSIMILARREQUESTDTO']._serialized_end=191
  _globals['_RAGRESPONSEDTO']._serialized_start=193
  _globals['_RAGRESPONSEDTO']._serialized_end=285
  _globals['_SEARCHVECTORRECORDITEMDTO']._serialized_start=287
  _globals['_SEARCHVECTORRECORDITEMDTO']._serialized_end=370
  _globals['_VECTORRECORDDTO']._serialized_start=372
  _globals['_VECTORRECORDDTO']._serialized_end=468
  _globals['_METADATAVECTORRECORDDTO']._serialized_start=471
  _globals['_METADATAVECTORRECORDDTO']._serialized_end=632
  _globals['_RAGSERVICE']._serialized_start=634
  _globals['_RAGSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
